const assert = require('node:assert/strict');

module.exports = async ({ base, tokenC, cliente, tokenP, prestador, db }) => {
  const { chromium } = require('playwright');
  const browser = await chromium.launch({ headless: true, channel: 'chrome', args: ['--use-fake-device-for-media-stream', '--use-fake-ui-for-media-stream'] });
  try {
    await db.atualizar('solicitacoes', 'regressao', { status: 'aberta' });
    const errors = [];
    async function participante(token, usuario, mobile = false) {
      const context = await browser.newContext({ viewport: mobile ? { width: 390, height: 844 } : { width: 1280, height: 900 } });
      await context.addInitScript(({ token, usuario }) => localStorage.setItem('contactme.sessao', JSON.stringify({ token, usuario })), { token, usuario });
      await context.route('https://fonts.googleapis.com/**', route => route.abort());
      await context.route('https://fonts.gstatic.com/**', route => route.abort());
      const page = await context.newPage();
      page.on('pageerror', e => errors.push(e.message));
      await page.goto(base + '/#/chat/regressao');
      await page.locator('#campoMensagem').waitFor();
      return page;
    }
    const c = await participante(tokenC, cliente, true);
    const p = await participante(tokenP, prestador);
    await c.locator('#temaSeletor').selectOption('escuro');
    assert.equal(await c.locator('html').getAttribute('data-tema'), 'escuro');
    await c.reload();
    assert.equal(await c.locator('#temaSeletor').inputValue(), 'escuro');
    await c.locator('#temaSeletor').selectOption('claro');
    await c.emulateMedia({ colorScheme: 'dark' });
    assert.equal(await c.locator('html').getAttribute('data-tema'), 'claro');
    await c.locator('#temaSeletor').selectOption('sistema');
    await c.waitForFunction(() => document.documentElement.dataset.tema === 'escuro');
    await c.emulateMedia({ colorScheme: 'light' });
    await c.waitForFunction(() => document.documentElement.dataset.tema === 'claro');
    await c.locator('#campoMensagem').fill('Mensagem do navegador cliente');
    await c.locator('.chat-enviar').click();
    await p.getByText('Mensagem do navegador cliente', { exact: false }).waitFor();
    assert.equal(await c.locator('.balao').filter({ hasText: 'Mensagem do navegador cliente' }).count(), 1);
    await p.locator('#campoMensagem').fill('Resposta do navegador prestador');
    await p.locator('#campoMensagem').press('Enter');
    await c.getByText('Resposta do navegador prestador', { exact: false }).waitFor();
    const foto = Buffer.from(await c.evaluate(() => {
      const canvas = document.createElement('canvas'); canvas.width = 320; canvas.height = 180;
      const ctx = canvas.getContext('2d'); ctx.fillStyle = '#7c9aaa'; ctx.fillRect(0, 0, 320, 180);
      ctx.fillStyle = '#d7cdb8'; ctx.fillRect(60, 30, 200, 150);
      ctx.fillStyle = '#384b43'; ctx.fillRect(135, 80, 50, 100);
      return canvas.toDataURL('image/png').split(',')[1];
    }), 'base64');
    assert.equal(await c.locator('#fotoCamera').getAttribute('capture'), 'environment');
    await c.locator('#fotoGaleria').setInputFiles({ name: 'obra.png', mimeType: 'image/png', buffer: foto });
    await c.locator('.chat-foto-previa img').waitFor();
    await c.locator('.chat-foto-previa button').click();
    assert.ok(await c.locator('.chat-foto-previa').isHidden());
    await c.locator('#fotoGaleria').setInputFiles({ name: 'obra.png', mimeType: 'image/png', buffer: foto });
    await c.locator('.chat-foto-previa img').waitFor();
    await c.locator('.chat-enviar').click();
    await p.waitForFunction(() => document.querySelector('.chat-foto-mensagem img')?.naturalWidth > 0);
    await p.locator('.chat-foto-mensagem').click();
    await p.locator('dialog img').waitFor();
    await p.keyboard.press('Escape');
    await c.reload();
    await c.waitForFunction(() => document.querySelector('.chat-foto-mensagem img')?.naturalWidth > 0);
    await p.locator('#abrirCamera').click();
    await p.waitForFunction(() => document.querySelector('[data-capturar]')?.disabled === false);
    await p.evaluate(() => { window.tracksTeste = document.querySelector('video').srcObject.getTracks(); });
    await p.locator('[data-capturar]').click();
    await p.locator('.chat-foto-previa img').waitFor();
    assert.ok(await p.evaluate(() => window.tracksTeste.every(t => t.readyState === 'ended')), 'câmera desligada após captura');
    await p.locator('#campoMensagem').fill('Foto tirada com a câmera');
    await p.locator('.chat-enviar').click();
    await c.getByText('Foto tirada com a câmera', { exact: false }).waitFor();
    await c.waitForFunction(() => [...document.querySelectorAll('.chat-foto-mensagem img')].length === 2 && [...document.querySelectorAll('.chat-foto-mensagem img')].every(i => i.naturalWidth > 0));
    await p.evaluate(() => { navigator.mediaDevices.getUserMedia = async () => { throw new DOMException('Negada', 'NotAllowedError'); }; });
    await p.locator('#abrirCamera').click();
    await p.getByText('Não foi possível acessar a câmera. Confira a permissão ou use a galeria.').waitFor();
    const pastaFotos = require('node:fs').mkdtempSync(require('node:path').join(require('node:os').tmpdir(), 'contactme-fotos-ui-'));
    await c.locator('#temaSeletor').selectOption('claro');
    await c.screenshot({ path: require('node:path').join(pastaFotos, 'chat-claro-celular.png'), fullPage: true, animations: 'disabled' });
    await p.locator('#temaSeletor').selectOption('escuro');
    await p.screenshot({ path: require('node:path').join(pastaFotos, 'chat-escuro-desktop.png'), fullPage: true, animations: 'disabled' });
    console.log('Capturas do chat: ' + pastaFotos);
    await c.route('**/api/chat/regressao/mensagens', route => route.request().method() === 'POST' ? route.abort() : route.continue());
    await c.locator('#fotoGaleria').setInputFiles({ name: 'obra.png', mimeType: 'image/png', buffer: foto });
    await c.locator('.chat-foto-previa img').waitFor();
    await c.locator('#campoMensagem').fill('Rascunho preservado na falha');
    await c.locator('.chat-enviar').click();
    await c.waitForFunction(() => document.getElementById('campoMensagem').value === 'Rascunho preservado na falha');
    assert.ok(await c.locator('.chat-foto-previa').isVisible(), 'foto preservada na falha de envio');
    await c.unroute('**/api/chat/regressao/mensagens');
    await p.locator('[data-status="recusada"]').click();
    await c.locator('#chatEncerrado').waitFor({ state: 'visible' });
    assert.equal(await c.locator('#formMensagem').isVisible(), false);
    assert.equal(await c.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await c.route('**/api/solicitacoes/regressao', async route => {
      await new Promise(resolve => setTimeout(resolve, 250));
      await route.continue();
    });
    await c.evaluate(() => { location.hash = '#/busca'; });
    await c.locator('#formBusca').waitFor();
    await c.screenshot({ path: require('node:path').join(pastaFotos, 'busca-claro-celular.png'), fullPage: true, animations: 'disabled' });
    const carregandoChat = c.waitForRequest('**/api/solicitacoes/regressao');
    await c.evaluate(() => { location.hash = '#/chat/regressao'; });
    await carregandoChat;
    await c.evaluate(() => { location.hash = '#/solicitacoes'; });
    await c.locator('#lista').waitFor();
    await c.waitForTimeout(500);
    assert.equal(await c.locator('#lista').count(), 1, 'resposta antiga não substitui a tela atual');
    await c.goto(base + '/admin.html');
    await c.locator('#temaSeletor').selectOption('escuro');
    assert.equal(await c.locator('html').getAttribute('data-tema'), 'escuro');
    await c.locator('#temaSeletor').selectOption('claro');
    assert.equal(await c.locator('html').getAttribute('data-tema'), 'claro');
    assert.deepEqual(errors, []);
    console.log('Navegador: chat entre dois perfis, falha de envio, encerramento remoto, mobile e três temas: OK');
  } finally { await browser.close(); }
};
